version: '3'

services:
  cloudflare-ddns:
    build: .
    container_name: cloudflare-ddns
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./static:/app/static
    environment:
      - RUST_LOG=info
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      # Cloudflare 設置 (可選，可以使用配置文件替代)
      # - CLOUDFLARE_API_TOKEN=your_cloudflare_api_token
      # - CLOUDFLARE_ZONE_ID=your_cloudflare_zone_id
      # - CLOUDFLARE_RECORD_ID=your_cloudflare_record_id
      # - CLOUDFLARE_RECORD_NAME=your.domain.com
      # - CLOUDFLARE_RECORD_ID_V6=your_cloudflare_record_id_v6
      # - CLOUDFLARE_RECORD_NAME_V6=your.domain.com
      # - DDNS_UPDATE_INTERVAL=300 